Downloader setup
texterify/texterify-ios pull request #1
Opened 2020-10-29 14:06 UTC by madlyn

The basic structure:
1- download the file generated by texterify
2- Decoding content 
3- Creating Custom bundle and localisation files accordingly

2020-10-29 14:47 UTC, mbuchetics commented on texterify-ios-sdk/Downloader.swift
> +        let dateFormatter = DateFormatter()
dateformatter should only be constructed once, e.g. make it a static

2020-10-29 14:47 UTC, mbuchetics commented on texterify-ios-sdk/Downloader.swift
> +        let locale = String(Locale.preferredLanguages.first?.description ?? "")
Locale.preferredLanguages gives use the language independent of what the app actually supports. E.g. if I add Japanese to my iOS preferred languages, it will return it here. But that's not what you want if your app only supports german and english for example.
You should use `Bundle.main` to get a list of the supported languages. Maybe optionally have the user pass the language code to the function here as well.

2020-10-29 14:47 UTC, mbuchetics commented on texterify-ios-sdk/Downloader.swift
> +                        try FileManager.default.removeItem(at: destinationUrl)
there is a `moveItem`function

2020-10-29 14:47 UTC, mbuchetics commented on texterify-ios-sdk/Downloader.swift
> +                let documentsUrl = FileManager.default.urls(for: .documentDirectory, in: .userDomainMask).first!
better avoid force unwrap

2020-10-29 14:47 UTC, mbuchetics commented on texterify-ios-sdk/Downloader.swift
> +                print("There was an error downloading the file: \(error.localizedDescription)\n")
errors should be exposed to the user of the framework somehow, e.g. by using a closure

2020-10-29 14:47 UTC, mbuchetics commented on texterify-ios-sdk/TexterifyManager.swift
> +    func constructStringFiles() {
I would split this function into different parts:
parse the json into your model
use the model to construct the Localizable.string pairs
write it to a file

makes it easier to replace parts of the implementation

2020-10-29 14:47 UTC, mbuchetics commented on texterify-ios-sdk/TexterifyManager.swift
> +            let localizationFile = localizationFolderURL.appendingPathComponent("Localization.strings")
should be Localizable.strings, right?

2020-10-29 14:47 UTC, mbuchetics commented on texterify-ios-sdk/TexterifyManager.swift
> +                try stringChange.write(to: localizationFile, atomically: true, encoding: .utf8)
isn't this only writing one pair and then overwriting it with the next one?
i would also avoid writing to the file that often (in a loop), instead construct the whole string and then write it once.

2020-10-29 14:47 UTC, mbuchetics commented on texterify-ios-sdk/TexterifyManager.swift
> +                let stringChange = "\"\(pair.key)\":\"\(pair.value)\";"
should be `=` instead of `:`

2020-10-29 18:45 UTC, madlyn commented on texterify-ios-sdk/TexterifyManager.swift
> +                let stringChange = "\"\(pair.key)\":\"\(pair.value)\";"
noticed and changed afterwards (facepalm)

2020-11-13 10:24 UTC, mbuchetics requested changes

2020-11-13 10:24 UTC, mbuchetics commented on texterify-ios-sdk/Downloader.swift
> +        guard let appLanguageCode = Locale.current.languageCode, let regionCode = Locale.current.regionCode else {
I think Locale.current will give you the iOS system setting, and not what's actually available in the app. E.g., set your phone to Spanish, but the app only supports English & German. what's the result here?

compare:
https://developer.apple.com/documentation/foundation/bundle/1417415-localizations
https://developer.apple.com/documentation/foundation/nslocale/1415614-preferredlanguages

2020-11-13 10:24 UTC, mbuchetics commented on texterify-ios-sdk/Downloader.swift
> +        Downloader.dateFormatter.dateFormat = "yyyy-MM-dd'T'HH:mm:ss'Z'"
you should only set the dateFormat once (e.g. when the formatter is created) and then keep reusing the same dateFormatter

2020-11-13 10:38 UTC, madlyn commented on texterify-ios-sdk/Downloader.swift
> +        guard let appLanguageCode = Locale.current.languageCode, let regionCode = Locale.current.regionCode else {
If I set the language of the phone to an unsupported language I get the en (base language of the app), so it seems to be the right way to go

2020-11-13 12:30 UTC, mbuchetics approved these changes

2020-11-20 07:05 UTC, merged